name: AI Auto-Fix & Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ai_fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install openai requests textblob numpy

      - name: AI Code Fix & Self-Improvement
        run: |
          python3 self_improve_ai.py  # This runs the AI improvement script

      - name: Commit & Push Changes
        run: |
          git config --global user.name "Janehandler"
          git config --global user.email "ender.zn.1914@gmail.com"
          git add .
          git commit -m "AI Auto-Updated Code"
          git push
